# This is a basic workflow to help you get started with Actions


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: step1
        uses: actions/checkout@v3
      - name: step2
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'Tiphaines site'
          path: './'
          pinata-api-key: a7bad8aa5b4cf40f2c55
          pinata-secret-api-key: 1bcaafa9d7999a3e91e5a9ba3446058c904349616f3738e3cd27a1860cb4502e
          verbose: true
          remove-old: false

      

      
